// ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
// Système typographique, espacement, statuts, charge — utilisable par tous
// les composants pour rester cohérent. Voir audit P06.

export const TYPE = {
  display:  { fontFamily: "'Newsreader', Georgia, serif", fontSize: 32, fontWeight: 500, lineHeight: 1.08, letterSpacing: "-0.01em" },
  title:    { fontFamily: "'Newsreader', Georgia, serif", fontSize: 22, fontWeight: 500, lineHeight: 1.2 },
  subtitle: { fontFamily: "'Newsreader', Georgia, serif", fontSize: 16, fontWeight: 500, lineHeight: 1.35 },
  body:     { fontFamily: "'Inter', system-ui, -apple-system, sans-serif", fontSize: 14, fontWeight: 400, lineHeight: 1.5 },
  label:    { fontFamily: "'Inter', system-ui, -apple-system, sans-serif", fontSize: 12, fontWeight: 500, lineHeight: 1.4 },
  caption:  { fontFamily: "'Inter', system-ui, -apple-system, sans-serif", fontSize: 11, fontWeight: 500, lineHeight: 1.4, letterSpacing: "0.06em", textTransform: "uppercase" },
  mono:     { fontFamily: "'JetBrains Mono', Menlo, Consolas, monospace", fontSize: 12 },
};

export const SPACE = {
  0: 0, 1: 4, 2: 8, 3: 12, 4: 16, 5: 20, 6: 24, 7: 32, 8: 48,
};

export const STATUS = (isDark) => ({
  done:     { bg: isDark ? "#1c2d20" : "#e3f0e5", fg: isDark ? "#7ab890" : "#2e6b3f" },
  adapted:  { bg: isDark ? "#2a2410" : "#fef2dc", fg: isDark ? "#d4a843" : "#b8881a" },
  moved:    { bg: isDark ? "#2a2410" : "#fef2dc", fg: isDark ? "#d4a843" : "#b8881a" },
  missed:   { bg: isDark ? "#2a1313" : "#fbecec", fg: isDark ? "#e87878" : "#b83030" },
});

export const chargeTokenColor = (value, isDark) => {
  if (!value || value < 4)  return { bg: isDark ? "#1c2d20" : "#e3f0e5", fg: isDark ? "#7ab890" : "#2e6b3f" };
  if (value < 7)            return { bg: isDark ? "#2a2410" : "#fef2dc", fg: isDark ? "#d4a843" : "#b8881a" };
  return                          { bg: isDark ? "#2a1a10" : "#fbecdc", fg: isDark ? "#c8906a" : "#b8651a" };
};

export function makeStyles(isDark) {
  const D = isDark;
  const t = {
    // ── Design tokens partagés ──
    type: TYPE,
    space: SPACE,
    status: STATUS(isDark),
    chargeColor: (v) => chargeTokenColor(v, isDark),
    serif: "'Newsreader', Georgia, serif",
    sans: "'Inter', system-ui, -apple-system, sans-serif",
    mono: "'JetBrains Mono', Menlo, Consolas, monospace",
    // ── Existants ──
    bg:              D ? "#191e1b"   : "#f0ebe2",
    surface:         D ? "#1f2421"   : "#e8e2d8",
    surface2:        D ? "#252b27"   : "#ddd7cc",
    border:          D ? "#252b27"   : "#ccc6b8",
    border2:         D ? "#2a3028"   : "#c4beb0",
    headerGrad:      D ? "linear-gradient(180deg, #1c2220 0%, #191e1b 100%)" : "linear-gradient(180deg, #e0d9ce 0%, #eae4da 100%)",
    text:            D ? "#e8e4de"   : "#2a2218",
    textTitle:       D ? "#c8c0b4"   : "#3a3028",
    textMuted:       D ? "#707870"   : "#8a7f70",
    textDim:         D ? "#7a8480"   : "#7a7060",
    textCard:        D ? "#b0a898"   : "#4a3f32",
    accent:          D ? "#c8906a"   : "#8b4c20",
    accentBg:        D ? "#2a1a10"   : "#ecddd4",
    accentBorder:    D ? "#c8906a66" : "#8b4c2066",
    accentFaint:     D ? "#c8906a44" : "#8b4c2044",
    accentSolid:     D ? "#c8906a55" : "#8b4c2055",
    btnBorder:       D ? "#2e3430"   : "#bfb9aa",
    navColor:        D ? "#909898"   : "#7a7060",
    gridGap:         D ? "#1f2421"   : "#d0c9bf",
    todayBg:         D ? "#221510"   : "#ecddd4",
    metabarBg:       D ? "#161b18"   : "#ece6dc",
    subtleBorder:    D ? "#222927"   : "#ccc6b8",
    modalBg:         D ? "#191e1b"   : "#ede8de",
    overlayBg:       D ? "rgba(0,0,0,0.70)" : "rgba(0,0,0,0.45)",
    actionColor:     D ? "#4a5450"   : "#8a7f70",
    dashedBorder:    D ? "#2a3028"   : "#c4beb0",
    sessionBorder:   D ? "#1e2421"   : "#d4cec4",
    negativeBg:      D ? "#301a1a"   : "#f8d8dc",
    negativeBorder:  D ? "#f43f5e66" : "#c0394e55",
    negativeColor:   D ? "#f43f5e"   : "#c0394e",
    inputBg:         D ? "#252b27"   : "#ddd7cc",
    starEmpty:       D ? "#555"      : "#bbb",
    badgeText:       D ? "#8a9898"   : "#5a6878",
    dayEmpty:        D ? "#252b27"   : "#ccc7bc",
  };

  return {
    app: {
      minHeight: "100vh", background: t.bg, color: t.text,
      fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
      position: "relative", display: "flex", flexDirection: "column",
    },
    grain: {
      position: "fixed", inset: 0, pointerEvents: "none", zIndex: 0,
      backgroundImage: "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E\")",
      opacity: D ? 0.4 : 0.15,
    },
    header: {
      display: "flex", alignItems: "center", justifyContent: "space-between",
      padding: "18px 24px 14px", borderBottom: `1px solid ${t.border2}`,
      position: "relative", zIndex: 1, background: t.headerGrad,
    },
    headerLeft: { display: "flex", alignItems: "center", gap: 12 },
    logo: { display: "flex", alignItems: "center" },
    appTitle: { fontSize: 15, fontWeight: 600, letterSpacing: "0.18em", color: t.textTitle, fontFamily: "'Newsreader', Georgia, serif" },
    appSub: { fontSize: 10, color: t.textMuted, letterSpacing: "0.1em", marginTop: 2 },
    weekNav: { display: "flex", alignItems: "center", gap: 16 },
    navBtn: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.navColor, cursor: "pointer",
      width: 34, height: 34, borderRadius: 6, fontSize: 16, display: "flex", alignItems: "center", justifyContent: "center",
      transition: "all 0.15s", flexShrink: 0,
    },
    weekLabel: { textAlign: "center", minWidth: 180 },
    weekRange: { fontSize: 16, color: t.textTitle, fontWeight: 500, letterSpacing: "0.05em", fontFamily: "'Newsreader', Georgia, serif" },
    weekCurrent: { fontSize: 10, color: t.accent, letterSpacing: "0.12em", marginTop: 3, textTransform: "uppercase" },
    headerRight: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 6 },
    headerRightTop: { display: "flex", alignItems: "center", gap: 8 },
    totalCharge: { textAlign: "right" },
    totalChargeNum: { fontSize: 28, fontWeight: 700, color: t.text, lineHeight: 1 },
    totalChargeLabel: { display: "block", fontSize: 9, color: t.textMuted, letterSpacing: "0.12em", textTransform: "uppercase", marginTop: 2 },

    headerMobile: {
      display: "flex", flexDirection: "column",
      borderBottom: `1px solid ${t.border2}`, position: "relative", zIndex: 1, background: t.headerGrad,
    },
    headerMobileRow1: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 16px 6px" },
    headerMobileRow2: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "4px 16px 8px" },
    headerMobileRight: { display: "flex", alignItems: "center", gap: 8 },
    weekNavMobile: {
      display: "flex", alignItems: "center", justifyContent: "space-between",
      padding: "6px 16px 10px", borderTop: `1px solid ${t.subtleBorder}`,
    },
    totalChargeMobile: { textAlign: "right" },

    viewToggle: { display: "flex", gap: 2 },
    viewToggleBtn: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim,
      padding: "4px 12px", borderRadius: 4, cursor: "pointer",
      fontSize: 10, fontFamily: "inherit", letterSpacing: "0.08em", transition: "all 0.15s",
    },
    viewToggleBtnActive: { background: t.accentBg, border: `1px solid ${t.accentBorder}`, color: t.accent },

    themeBtn: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim,
      width: 28, height: 28, borderRadius: 4, cursor: "pointer",
      fontSize: 14, fontFamily: "inherit", display: "flex", alignItems: "center", justifyContent: "center",
      transition: "all 0.15s",
    },
    profileBtn: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim,
      width: 28, height: 28, borderRadius: "50%", cursor: "pointer",
      fontSize: 14, fontFamily: "inherit", display: "flex", alignItems: "center", justifyContent: "center",
      transition: "all 0.15s", overflow: "hidden", padding: 0,
    },

    syncBtns: { display: "flex", gap: 4 },
    syncBtn: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim,
      padding: "4px 10px", borderRadius: 4, cursor: "pointer",
      fontSize: 10, fontFamily: "inherit", letterSpacing: "0.06em", transition: "all 0.15s",
    },
    syncBtnCompact: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim,
      width: 28, height: 28, borderRadius: 4, cursor: "pointer",
      fontSize: 13, fontFamily: "inherit", display: "flex", alignItems: "center", justifyContent: "center",
      transition: "all 0.15s",
    },
    syncDot: { fontSize: 12, lineHeight: 1, transition: "color 0.3s" },

    authBar: { display: "flex", alignItems: "center", gap: 8, paddingTop: 4 },
    authInput: {
      background: t.inputBg, border: `1px solid ${t.btnBorder}`, color: t.textTitle,
      padding: "5px 10px", borderRadius: 5, fontSize: 11, fontFamily: "inherit", width: 170, outline: "none",
    },
    authBtn: {
      background: t.accentBg, border: `1px solid ${t.accentBorder}`, color: t.accent,
      padding: "5px 12px", borderRadius: 5, cursor: "pointer",
      fontSize: 11, fontFamily: "inherit", letterSpacing: "0.06em", transition: "all 0.15s",
    },
    authEmail: { fontSize: 10, color: t.textMuted, letterSpacing: "0.06em" },
    authLogoutBtn: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim,
      padding: "4px 10px", borderRadius: 4, cursor: "pointer", fontSize: 10, fontFamily: "inherit", letterSpacing: "0.06em",
    },
    authSentMsg: { fontSize: 11, color: t.accent, letterSpacing: "0.06em" },
    authErrorMsg: { fontSize: 11, color: "#f97316", letterSpacing: "0.04em" },
    headerMobileRow3: { padding: "4px 16px 10px", borderTop: `1px solid ${t.subtleBorder}` },

    metaBar: {
      padding: "8px 24px", borderBottom: `1px solid ${t.surface2}`,
      minHeight: 42, display: "flex", alignItems: "center", position: "relative", zIndex: 1, background: t.metabarBg,
    },
    metaDisplay: { display: "flex", alignItems: "center", gap: 10, cursor: "pointer", padding: "4px 0", width: "100%" },
    metaPlaceholder: { fontSize: 11, color: t.textMuted, letterSpacing: "0.08em" },
    mesoTag: { fontSize: 11, padding: "3px 10px", borderRadius: 4, border: "1px solid", fontWeight: 600, letterSpacing: "0.06em" },
    microTag: { fontSize: 11, color: t.navColor, background: t.surface2, padding: "3px 10px", borderRadius: 4 },
    noteTag: { fontSize: 11, color: t.textDim, fontStyle: "italic" },
    metaForm: { display: "flex", gap: 8, alignItems: "center", width: "100%" },
    metaSelect: {
      background: t.inputBg, border: `1px solid ${t.btnBorder}`, color: t.textTitle,
      padding: "5px 10px", borderRadius: 5, fontSize: 11, fontFamily: "inherit",
    },
    metaInput: {
      background: t.inputBg, border: `1px solid ${t.btnBorder}`, color: t.textTitle,
      padding: "5px 10px", borderRadius: 5, fontSize: 11, fontFamily: "inherit", flex: 1,
    },

    grid: {
      display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gridTemplateRows: "1fr",
      gap: 1, flex: 1, background: t.gridGap, position: "relative", zIndex: 1, minHeight: 0, overflow: "hidden",
    },
    gridMobile: { display: "flex", flexDirection: "column", background: t.gridGap, gap: 1, position: "relative", zIndex: 1 },
    dayCol: {
      background: t.bg, display: "flex", flexDirection: "column",
      padding: "10px 8px", minHeight: 0, overflow: "hidden", position: "relative", transition: "background 0.15s",
    },
    dayColMobile: { minHeight: 0, flex: 1, padding: 0, borderBottom: "none" },
    dayColToday: { background: t.todayBg, borderTop: `2px solid ${t.accent}` },
    dayHeader: { display: "flex", flexDirection: "column", gap: 1, marginBottom: 10, paddingBottom: 8, borderBottom: `1px solid ${t.border}` },
    dayHeaderMobile: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 8, paddingBottom: 8, borderBottom: `1px solid ${t.border}` },
    dayHeaderMobileLeft: { display: "flex", alignItems: "center", gap: 8 },
    dayName: { fontSize: 11, fontWeight: 700, letterSpacing: "0.14em", color: t.textDim, textTransform: "uppercase" },
    dayNameToday: { color: t.accent },
    dayDate: { fontSize: 10, color: t.textMuted },
    dayCharge: { fontSize: 13, fontWeight: 700, marginTop: 2 },

    sessionCards: { display: "flex", flexDirection: "column", gap: 5, flex: 1 },
    sessionCard: {
      background: t.surface, border: `1px solid ${t.border}`,
      borderRadius: 5, display: "flex", alignItems: "stretch",
      overflow: "hidden", cursor: "default", transition: "border-color 0.15s",
    },
    sessionCardAccent: { width: 3, flexShrink: 0 },
    sessionCardContent: { flex: 1, padding: "5px 7px" },
    sessionCardName: { fontSize: 10, color: t.textCard, display: "block", lineHeight: 1.4, letterSpacing: "0.02em" },
    sessionCardFooter: { display: "flex", alignItems: "center", gap: 6, marginTop: 3 },
    sessionCardCharge: { fontSize: 10, fontWeight: 700 },
    feedbackDot: { fontSize: 10, color: t.accent },
    sessionCardActions: { display: "flex", flexDirection: "column" },
    actionBtn: {
      background: "none", border: "none", color: t.actionColor, cursor: "pointer",
      padding: "3px 5px", fontSize: 10, lineHeight: 1, transition: "color 0.1s", flex: 1,
    },
    addBtn: {
      marginTop: 8, background: "none", border: `1px dashed ${t.dashedBorder}`,
      color: t.actionColor, cursor: "pointer", borderRadius: 5,
      padding: "6px 4px", display: "flex", alignItems: "center", justifyContent: "center",
      gap: 4, fontSize: 10, letterSpacing: "0.06em", transition: "all 0.15s", width: "100%",
    },
    addBtnIcon: { fontSize: 12, lineHeight: 1 },
    addBtnLabel: {},

    chargeBar: {
      display: "grid", gridTemplateColumns: "repeat(7, 1fr)",
      gap: 1, background: t.gridGap, padding: "8px 0 10px", position: "relative", zIndex: 1,
    },
    chargeBarCol: { display: "flex", flexDirection: "column", alignItems: "center", gap: 3 },
    chargeBarTrack: {
      width: 6, height: 40, background: t.surface2, borderRadius: 3,
      display: "flex", alignItems: "flex-end", overflow: "hidden",
    },
    chargeBarFill: { width: "100%", borderRadius: 3, transition: "height 0.3s, background 0.3s" },
    chargeBarLabel: { fontSize: 9, fontWeight: 700, letterSpacing: "0.04em" },
    chargeBarLabelEmpty: t.textMuted,

    monthView: { flex: 1, position: "relative", zIndex: 1, padding: "16px 24px", overflowY: "auto" },
    monthDayHeaders: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 2, marginBottom: 6 },
    monthDayHeaderCell: { textAlign: "center", fontSize: 10, color: t.textMuted, letterSpacing: "0.12em", textTransform: "uppercase", padding: "4px 0" },
    monthWeekRow: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 2, marginBottom: 2 },
    monthDayCell: {
      background: t.surface, border: `1px solid ${t.border}`,
      borderRadius: 5, padding: "7px 8px", minHeight: 100,
      cursor: "pointer", display: "flex", flexDirection: "column",
      transition: "border-color 0.15s", position: "relative", overflow: "hidden",
    },
    monthDayCellMobile: { minHeight: 64, padding: "5px 4px" },
    monthDayCellOut: { opacity: 0.25, cursor: "default" },
    monthDayCellToday: { borderColor: t.accentSolid, background: t.todayBg },
    monthDayNum: { fontSize: 12, fontWeight: 600, color: t.textDim, lineHeight: 1 },
    monthDayNumToday: { color: t.accent },
    monthDayContent: { display: "flex", flexDirection: "column", gap: 2, marginTop: 5, flex: 1 },
    monthSessionRow: { borderRadius: 3, padding: "2px 5px" },
    monthSessionLabel: { fontSize: 9, display: "block", letterSpacing: "0.02em", lineHeight: 1.35 },
    monthMoreLabel: { fontSize: 9, color: t.textMuted, letterSpacing: "0.04em", paddingLeft: 2 },
    monthDayChargeBar: { position: "absolute", bottom: 0, left: 0, right: 0, height: 3, borderRadius: "0 0 5px 5px" },
    monthMobileDots: { display: "flex", gap: 2, marginTop: 4, flexWrap: "wrap" },
    monthMobileDot: { width: 5, height: 5, borderRadius: "50%" },

    yearGrid: {
      flex: 1, position: "relative", zIndex: 1, padding: "16px 24px",
      display: "grid", gridTemplateColumns: "repeat(4, 1fr)",
      gap: 8, alignContent: "start", overflowY: "auto",
    },
    yearGridMobile: { gridTemplateColumns: "repeat(2, 1fr)", padding: "12px 16px" },
    yearMonthCard: {
      background: t.surface, border: `1px solid ${t.border}`,
      borderRadius: 7, padding: "12px", cursor: "pointer", transition: "border-color 0.15s",
    },
    yearMonthCardCurrent: { borderColor: t.accentFaint, background: t.todayBg },
    yearMonthHeader: { display: "flex", alignItems: "baseline", justifyContent: "space-between", marginBottom: 8 },
    yearMonthName: { fontSize: 11, fontWeight: 600, color: t.navColor, letterSpacing: "0.04em" },
    yearMonthNameCurrent: { color: t.accent },
    yearMonthCharge: { fontSize: 13, fontWeight: 700 },
    yearHeatmap: { display: "flex", flexDirection: "column", gap: 2 },
    yearHeatmapRow: { display: "grid", gridTemplateColumns: "repeat(7, 1fr)", gap: 2 },
    yearHeatmapCell: { height: 14, borderRadius: 2 },
    yearDayEmpty: t.dayEmpty,

    dashboard: { padding: "20px 24px", overflowY: "auto", flex: 1 },
    dashTitle: { fontSize: 11, fontWeight: 700, color: t.navColor, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 20 },
    dashCards: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 12, marginBottom: 28 },
    dashCard: {
      background: t.surface, border: `1px solid ${t.border}`, borderRadius: 8,
      padding: "14px 16px", display: "flex", flexDirection: "column", gap: 4,
    },
    dashCardVal: { fontSize: 24, fontWeight: 700, color: t.text, lineHeight: 1 },
    dashCardLabel: { fontSize: 10, color: t.textMuted, letterSpacing: "0.06em", textTransform: "uppercase" },
    dashSection: { marginBottom: 28 },
    dashSectionTitle: { fontSize: 14, fontWeight: 600, color: t.navColor, letterSpacing: "0.07em", textTransform: "uppercase", marginBottom: 10, fontFamily: "'Newsreader', Georgia, serif" },
    dashChartBg: t.surface,
    dashGrid: t.border,
    dashText: t.textMuted,
    dashTooltipBg: t.surface,
    dashTooltipText: t.text,
    // ── Sleep ──
    sleepImportBtn: { fontSize: 11, padding: "4px 10px", borderRadius: 5, border: `1px solid ${t.border2}`, background: t.accentFaint, color: t.accent, cursor: "pointer", fontFamily: "inherit", letterSpacing: "0.03em", whiteSpace: "nowrap" },
    sleepEmptyMsg: { textAlign: "center", padding: "28px 0", color: t.textMuted, fontSize: 12 },
    sleepCard: { background: t.surface, border: `1px solid ${t.border}`, borderRadius: 8, padding: "10px 14px", display: "flex", flexDirection: "column", gap: 4, flex: "1 1 80px" },
    sleepLegend: { display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 8 },
    sleepLegendDot: { width: 8, height: 8, borderRadius: "50%", display: "inline-block", marginRight: 4 },

    // ── Profile view ──
    profileView: { padding: "20px 24px", overflowY: "auto", flex: 1, maxWidth: 600, margin: "0 auto", width: "100%" },
    profileAvatar: { width: 96, height: 96, borderRadius: "50%", background: t.surface, border: `2px solid ${t.border2}`, overflow: "hidden", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, transition: "border-color 0.15s" },
    profileAvatarHint: { fontSize: 10, color: t.accent, marginTop: 6, cursor: "pointer", letterSpacing: "0.05em" },
    profileNameInput: { background: t.inputBg, border: `1px solid ${t.btnBorder}`, borderRadius: 5, padding: "8px 12px", color: t.text, fontSize: 13, fontFamily: "inherit", outline: "none", width: "100%" },
    profileSection: { marginBottom: 28 },
    profileSectionTitle: { fontSize: 10, fontWeight: 700, color: t.textMuted, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: 12, paddingBottom: 6, borderBottom: `1px solid ${t.border}` },
    profileRow: { display: "flex", gap: 12, marginBottom: 10, alignItems: "center" },
    profileSaveBtn: { background: t.accentBg, border: `1px solid ${t.accentBorder}`, color: t.accent, padding: "7px 18px", borderRadius: 5, cursor: "pointer", fontSize: 11, fontFamily: "inherit", letterSpacing: "0.06em" },
    profileCancelBtn: { background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim, padding: "7px 14px", borderRadius: 5, cursor: "pointer", fontSize: 11, fontFamily: "inherit" },
    cropOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.82)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 200, backdropFilter: "blur(6px)" },
    cropModal: { background: t.surface, border: `1px solid ${t.border2}`, borderRadius: 12, padding: "20px", width: "min(360px, 94vw)", boxShadow: "0 32px 96px rgba(0,0,0,0.5)" },

    // ── Cycles view ──
    cyclesView: { padding: "20px 24px", overflowY: "auto", flex: 1 },
    cyclesHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 20 },
    cyclesTitle: { fontSize: 11, fontWeight: 700, color: t.navColor, letterSpacing: "0.1em", textTransform: "uppercase" },
    cycleCard: { background: t.surface, border: `1px solid ${t.border}`, borderRadius: 8, marginBottom: 12, overflow: "hidden" },
    cycleMesoRow: { display: "flex", alignItems: "center", gap: 10, padding: "12px 14px", flexWrap: "wrap" },
    cycleColorInput: { width: 28, height: 28, borderRadius: 4, border: `1px solid ${t.border}`, padding: 0, cursor: "pointer", background: "none" },
    cycleLabelInput: { flex: "1 1 160px", background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 4, padding: "5px 9px", color: t.text, fontSize: 13, fontFamily: "inherit", fontWeight: 600 },
    cycleDurInput: { width: 52, background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 4, padding: "5px 7px", color: t.text, fontSize: 12, fontFamily: "inherit", textAlign: "center" },
    cycleDescInput: { flex: "2 1 200px", background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 4, padding: "5px 9px", color: t.textDim, fontSize: 11, fontFamily: "inherit" },
    cycleMicroList: { borderTop: `1px solid ${t.border}`, padding: "8px 14px 12px" },
    cycleMicroRow: { display: "flex", alignItems: "center", gap: 8, marginBottom: 6 },
    cycleMicroDot: { width: 6, height: 6, borderRadius: "50%", flexShrink: 0 },
    cycleMicroLabelInput: { flex: "1 1 140px", background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 4, padding: "4px 8px", color: t.text, fontSize: 12, fontFamily: "inherit" },
    cycleMicroDurInput: { width: 44, background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 4, padding: "4px 6px", color: t.textDim, fontSize: 11, fontFamily: "inherit", textAlign: "center" },
    cycleDeleteBtn: { background: "none", border: "none", color: t.textMuted, cursor: "pointer", fontSize: 14, padding: "2px 6px", borderRadius: 4 },
    confirmOverlay: { position: "fixed", inset: 0, background: t.overlayBg, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 200, backdropFilter: "blur(4px)" },
    confirmModal: { background: t.surface, border: `1px solid ${t.border}`, borderRadius: 10, padding: "20px 24px", width: "min(300px, 90vw)", boxShadow: "0 8px 32px rgba(0,0,0,0.4)", display: "flex", flexDirection: "column", gap: 14 },
    confirmTitle: { fontSize: 14, fontWeight: 600, color: t.text, textAlign: "center" },
    confirmSub: { fontSize: 12, color: t.textDim, textAlign: "center", marginTop: -6 },
    confirmBtnRow: { display: "flex", gap: 8, justifyContent: "center" },
    confirmDeleteBtn: { background: "#b83030", border: "none", borderRadius: 6, color: "#fff", padding: "8px 22px", fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "inherit" },
    confirmCancelBtn: { background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 6, color: t.text, padding: "8px 22px", fontSize: 13, cursor: "pointer", fontFamily: "inherit" },
    cycleAddMicroBtn: { fontSize: 11, color: t.accent, background: t.accentFaint, border: `1px dashed ${t.accentBorder}`, borderRadius: 4, padding: "4px 12px", cursor: "pointer", fontFamily: "inherit", marginTop: 4 },
    cycleAddMesoBtn: { fontSize: 11, color: t.accent, background: t.accentFaint, border: `1px dashed ${t.accentBorder}`, borderRadius: 6, padding: "8px 16px", cursor: "pointer", fontFamily: "inherit", letterSpacing: "0.04em" },
    cycleDurLabel: { fontSize: 10, color: t.textMuted },
    // ── Custom cycles section ──
    customCyclesSection: { marginTop: 32, borderTop: `1px solid ${t.border}`, paddingTop: 20 },
    customCyclesSectionHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
    customCyclesSectionTitle: { fontSize: 13, fontWeight: 700, color: t.text, letterSpacing: "0.04em" },
    customCycleRow: { display: "flex", alignItems: "center", gap: 10, padding: "8px 12px", background: t.inputBg, borderRadius: 6, marginBottom: 6, border: `1px solid ${t.border}` },
    customCycleColorSwatch: { width: 12, height: 36, borderRadius: 3, flexShrink: 0 },
    customCycleInfo: { flex: 1, display: "flex", flexDirection: "column", gap: 2, minWidth: 0 },
    customCycleName: { fontSize: 13, fontWeight: 500, color: t.text, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
    customCycleDate: { fontSize: 10, color: t.textDim },
    customCycleBars: { marginTop: "auto", display: "flex", flexDirection: "column", gap: 1, paddingBottom: 5, paddingTop: 2 },
    customCycleBar: { height: 3, borderRadius: 1.5, opacity: 0.85 },
    customCycleDots: { display: "flex", gap: 2, paddingTop: 2, flexWrap: "wrap" },
    customCycleDot: { width: 5, height: 5, borderRadius: "50%", opacity: 0.9 },
    // ── Timeline ──
    timelineWrap: { padding: "20px 24px", overflowY: "auto", flex: 1, display: "flex", flexDirection: "column" },
    timelineTopBar: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 28 },
    timelineTitle: { fontSize: 13, fontWeight: 700, color: t.text, letterSpacing: "0.06em", textTransform: "uppercase" },
    timelineEditBtn: { display: "flex", alignItems: "center", gap: 6, background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 6, color: t.textDim, padding: "6px 14px", fontSize: 12, cursor: "pointer", fontFamily: "inherit" },
    timelineSaveBtn: { display: "flex", alignItems: "center", gap: 8, background: t.accentBg, border: `1px solid ${t.accentBorder}`, borderRadius: 7, color: t.accent, padding: "10px 22px", fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "inherit", letterSpacing: "0.03em", marginTop: 32, alignSelf: "center" },
    timelineRow: { display: "flex", alignItems: "stretch", marginBottom: 10, gap: 0 },
    timelineLabelCol: { width: 148, flexShrink: 0, paddingRight: 14, display: "flex", flexDirection: "column", justifyContent: "center", gap: 2 },
    timelineLabelName: { fontSize: 12, fontWeight: 600, color: t.text, display: "flex", alignItems: "center", gap: 7 },
    timelineLabelDot: { width: 9, height: 9, borderRadius: "50%", flexShrink: 0 },
    timelineLabelMeta: { fontSize: 10, color: t.textDim, paddingLeft: 16 },
    timelineBarArea: { flex: 1, display: "flex", alignItems: "center", minWidth: 0 },
    timelineBar: { height: 38, borderRadius: 6, display: "flex", overflow: "hidden", position: "relative", minWidth: 24, border: "1px solid" },
    timelineMicroSeg: { height: "100%", display: "flex", alignItems: "center", justifyContent: "center", padding: "0 6px", cursor: "pointer", overflow: "hidden", flexShrink: 0, borderRight: "1px solid" },
    timelineMicroLabel: { fontSize: 9, fontWeight: 600, lineHeight: 1.3, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", textAlign: "center" },
    timelineMicroSub: { fontSize: 8, opacity: 0.65, textAlign: "center", lineHeight: 1 },
    timelineCustomRow: { display: "flex", alignItems: "center", marginBottom: 7, gap: 0 },
    timelineCustomBar: { height: 20, borderRadius: 4, display: "flex", alignItems: "center", padding: "0 8px", overflow: "hidden", border: "1px solid" },
    timelineSectionSep: { borderTop: `1px solid ${t.border}`, paddingTop: 16, marginTop: 20, marginBottom: 14, fontSize: 10, fontWeight: 700, color: t.textMuted, textTransform: "uppercase", letterSpacing: "0.1em" },
    timelinePopoverWrap: { position: "fixed", inset: 0, zIndex: 300 },
    timelinePopover: { position: "fixed", background: t.surface, border: `1px solid ${t.border}`, borderRadius: 8, padding: "12px 16px", minWidth: 160, maxWidth: 240, boxShadow: "0 8px 28px rgba(0,0,0,0.35)", zIndex: 301 },
    timelinePopoverTitle: { fontSize: 13, fontWeight: 600, color: t.text, marginBottom: 4 },
    timelinePopoverMeta: { fontSize: 11, color: t.textDim },
    cycleDateInput: { background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 4, padding: "4px 8px", color: t.text, fontSize: 11, fontFamily: "inherit", colorScheme: D ? "dark" : "light" },
    cycleDateEnd: { fontSize: 10, color: t.textMuted, whiteSpace: "nowrap", flexShrink: 0 },
    cycleMicroDate: { fontSize: 10, color: t.textDim, whiteSpace: "nowrap", flexShrink: 0, minWidth: 52 },
    // ── Custom session form ──
    customFormOverlay: { position: "fixed", inset: 0, background: t.overlayBg, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 250, backdropFilter: "blur(4px)" },
    customForm: { background: t.modalBg, border: `1px solid ${t.border2}`, borderRadius: 10, width: "min(680px, 96vw)", maxHeight: "92vh", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: D ? "0 24px 80px rgba(0,0,0,0.6)" : "0 24px 80px rgba(0,0,0,0.15)" },
    customFormBody: { overflowY: "auto", padding: "18px 20px", display: "flex", flexDirection: "column", gap: 14, flex: 1 },
    customFormRow: { display: "flex", gap: 10, alignItems: "center" },
    customFormField: { display: "flex", flexDirection: "column", gap: 5 },
    customFormLabel: { fontSize: 10, color: t.textMuted, letterSpacing: "0.07em", textTransform: "uppercase" },
    customFormInput: { background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 5, padding: "7px 10px", color: t.text, fontSize: 13, fontFamily: "inherit", outline: "none", width: "100%" },
    customFormSelect: { background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 5, padding: "7px 10px", color: t.text, fontSize: 12, fontFamily: "inherit", outline: "none", cursor: "pointer" },
    customFormTextarea: { background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 5, padding: "8px 10px", color: t.text, fontSize: 12, fontFamily: "inherit", outline: "none", width: "100%", resize: "vertical", lineHeight: 1.6 },
    customFormHint: { fontSize: 10, color: t.textMuted, letterSpacing: "0.04em", fontStyle: "italic" },
    customFormSectionTabs: { display: "flex", gap: 6, borderBottom: `1px solid ${t.border}`, paddingBottom: 8, marginBottom: 8 },
    customFormSectionTab: { fontSize: 11, padding: "4px 10px", borderRadius: 4, border: `1px solid ${t.border}`, background: "none", color: t.textDim, cursor: "pointer", fontFamily: "inherit", letterSpacing: "0.04em" },
    customFormSectionTabActive: { background: t.accentBg, borderColor: t.accentBorder, color: t.accent },
    customFormChargeRow: { display: "flex", alignItems: "center", gap: 12 },
    customFormChargeVal: { fontSize: 18, fontWeight: 700, minWidth: 32 },
    customFormSlider: { flex: 1, accentColor: t.accent },
    mesoHint: { fontSize: 10, color: t.navColor, letterSpacing: "0.04em", padding: "4px 8px", background: t.accentFaint, borderRadius: 4, display: "inline-flex", gap: 6 },
    // ── Charge calculator ──
    calcBtn: { fontSize: 11, padding: "2px 8px", borderRadius: 4, border: `1px solid ${t.border2}`, background: t.accentFaint, color: t.accent, cursor: "pointer", fontFamily: "inherit", letterSpacing: "0.03em", whiteSpace: "nowrap" },
    calcPanel: { background: t.surface2, border: `1px solid ${t.border2}`, borderRadius: 7, padding: "12px 14px", display: "flex", flexDirection: "column", gap: 10 },
    calcRow: { display: "flex", gap: 10, alignItems: "flex-end", flexWrap: "wrap" },
    calcField: { display: "flex", flexDirection: "column", gap: 4, flex: "1 1 100px" },
    calcLabel: { fontSize: 10, color: t.textMuted, letterSpacing: "0.07em", textTransform: "uppercase" },
    calcSelect: { background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 5, padding: "6px 8px", color: t.text, fontSize: 12, fontFamily: "inherit", outline: "none", cursor: "pointer" },
    calcInput: { background: t.inputBg, border: `1px solid ${t.border}`, borderRadius: 5, padding: "6px 8px", color: t.text, fontSize: 12, fontFamily: "inherit", outline: "none", width: "100%" },
    calcResultRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
    calcResultVal: { fontSize: 20, fontWeight: 700 },
    calcApplyBtn: { fontSize: 12, padding: "5px 14px", borderRadius: 5, border: "none", background: t.accent, color: "#fff", cursor: "pointer", fontFamily: "inherit", fontWeight: 600 },
    calcVolumeHint: { fontSize: 10, color: t.textDim, fontStyle: "italic" },
    // ── Info panel (reference tables) ──
    infoOverlay: { position: "fixed", inset: 0, background: t.overlayBg, display: "flex", alignItems: "center", justifyContent: "center", zIndex: 200, backdropFilter: "blur(4px)" },
    infoPanel: { background: t.modalBg, border: `1px solid ${t.border2}`, borderRadius: 10, width: "min(720px, 96vw)", maxHeight: "88vh", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: D ? "0 24px 80px rgba(0,0,0,0.6)" : "0 24px 80px rgba(0,0,0,0.15)" },
    infoPanelBody: { overflowY: "auto", padding: "16px 20px", display: "flex", flexDirection: "column", gap: 20 },
    infoTableTitle: { fontSize: 11, fontWeight: 700, color: t.accent, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 6 },
    infoTable: { width: "100%", borderCollapse: "collapse", fontSize: 11 },
    infoTh: { padding: "5px 8px", background: t.surface2, color: t.textMuted, fontWeight: 600, letterSpacing: "0.05em", textAlign: "left", borderBottom: `1px solid ${t.border}`, fontSize: 10 },
    infoTd: { padding: "5px 8px", color: t.text, borderBottom: `1px solid ${t.border}`, verticalAlign: "top" },
    infoIndexBadge: { display: "inline-block", minWidth: 20, textAlign: "center", fontWeight: 700, borderRadius: 3, padding: "1px 4px", fontSize: 11 },
    // ── Rich text ──
    richText: { fontSize: 12, color: t.text, lineHeight: 1.7, padding: "8px 0" },
    richUl: { paddingLeft: 16, display: "flex", flexDirection: "column", gap: 2 },
    richLi: { display: "flex", gap: 6, alignItems: "flex-start" },
    richBullet: { color: t.accent, flexShrink: 0, marginTop: 3 },
    richCheckbox: { width: 13, height: 13, borderRadius: 3, border: `1px solid ${t.border2}`, background: "none", flexShrink: 0, marginTop: 3, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
    richCheckboxDone: { background: t.accent, borderColor: t.accent },
    richImg: { maxWidth: "100%", borderRadius: 6, marginTop: 4 },
    richLink: { color: t.accent, textDecoration: "none" },
    // ── Detail modal ──
    detailModal: { background: t.modalBg, border: `1px solid ${t.border2}`, borderRadius: 10, width: "min(600px, 96vw)", maxHeight: "88vh", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: D ? "0 24px 80px rgba(0,0,0,0.6)" : "0 24px 80px rgba(0,0,0,0.15)" },
    detailBody: { overflowY: "auto", padding: "16px 20px", flex: 1 },
    detailSection: { marginBottom: 16 },
    detailSectionTitle: { fontSize: 10, fontWeight: 700, color: t.textMuted, letterSpacing: "0.09em", textTransform: "uppercase", marginBottom: 6, paddingBottom: 4, borderBottom: `1px solid ${t.border}` },
    detailMeta: { display: "flex", gap: 12, flexWrap: "wrap", marginBottom: 14 },
    detailMetaChip: { fontSize: 11, color: t.textCard, background: t.surface2, padding: "3px 10px", borderRadius: 12 },
    detailMesoBar: { display: "flex", gap: 8, marginBottom: 14, flexWrap: "wrap" },
    // ── Session card extras ──
    sessionCardMeso: { fontSize: 9, letterSpacing: "0.05em", padding: "1px 6px", borderRadius: 3, fontWeight: 600, marginTop: 2, alignSelf: "flex-start" },
    sessionCardDetailBtn: { fontSize: 11, background: "none", border: "none", color: t.textMuted, cursor: "pointer", padding: "2px 4px" },
    customBadge: { fontSize: 9, background: t.accentFaint, color: t.accent, padding: "1px 5px", borderRadius: 3, letterSpacing: "0.04em", border: `1px solid ${t.accentBorder}`, alignSelf: "flex-start" },
    // ── Custom session in picker ──
    customPickerSection: { padding: "10px 16px 4px", borderTop: `1px solid ${t.border}` },
    customPickerLabel: { fontSize: 10, color: t.textMuted, letterSpacing: "0.07em", textTransform: "uppercase", marginBottom: 8 },
    createCustomBtn: { width: "100%", padding: "10px 14px", background: t.accentFaint, border: `1px dashed ${t.accentBorder}`, borderRadius: 6, color: t.accent, fontSize: 12, cursor: "pointer", fontFamily: "inherit", letterSpacing: "0.04em", textAlign: "left" },

    overlay: {
      position: "fixed", inset: 0, background: t.overlayBg,
      display: "flex", alignItems: "center", justifyContent: "center",
      zIndex: 100, backdropFilter: "blur(4px)",
    },
    modal: {
      background: t.modalBg, border: `1px solid ${t.border2}`,
      borderRadius: 10, width: "90%", maxWidth: 520,
      maxHeight: "80vh", display: "flex", flexDirection: "column",
      overflow: "hidden", boxShadow: D ? "0 24px 80px rgba(0,0,0,0.6)" : "0 24px 80px rgba(0,0,0,0.15)",
    },
    modalHeader: { padding: "16px 18px", borderBottom: `1px solid ${t.border}`, display: "flex", alignItems: "center", justifyContent: "space-between" },
    modalTitle: { fontSize: 17, fontWeight: 600, letterSpacing: "0.08em", color: t.textTitle, fontFamily: "'Newsreader', Georgia, serif" },
    closeBtn: { background: "none", border: "none", color: t.textMuted, cursor: "pointer", fontSize: 16 },
    modalFilters: { padding: "12px 16px", borderBottom: `1px solid ${t.border}`, display: "flex", flexDirection: "column", gap: 8 },
    searchInput: {
      background: t.inputBg, border: `1px solid ${t.btnBorder}`, color: t.textTitle,
      padding: "8px 12px", borderRadius: 6, fontSize: 12, fontFamily: "inherit", outline: "none",
    },
    filterTabs: { display: "flex", gap: 6 },
    filterTab: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim,
      padding: "4px 12px", borderRadius: 4, cursor: "pointer", fontSize: 11, fontFamily: "inherit", letterSpacing: "0.06em",
    },
    filterTabActive: { background: t.accentBg, border: `1px solid ${t.accentBorder}`, color: t.accent },
    sessionList: { overflowY: "auto", flex: 1 },
    sessionItem: {
      display: "flex", alignItems: "center", justifyContent: "space-between",
      padding: "10px 16px", cursor: "pointer", borderBottom: `1px solid ${t.sessionBorder}`, transition: "background 0.1s",
    },
    sessionItemLeft: { display: "flex", alignItems: "center", gap: 10 },
    sessionTypeBadge: { fontSize: 9, padding: "2px 7px", borderRadius: 3, color: t.badgeText, letterSpacing: "0.08em", textTransform: "uppercase" },
    seanceBadgeBg: D ? "#1e3a5f" : "#c4d8ee",
    exerciceBadgeBg: D ? "#1a2e1a" : "#c4e0c8",
    sessionItemName: { fontSize: 12, color: t.textCard },
    chargePill: { fontSize: 11, fontWeight: 700, padding: "2px 8px", borderRadius: 4 },
    emptySearch: { padding: 20, textAlign: "center", color: t.textMuted, fontSize: 12 },

    feedbackSubtitle: { fontSize: 10, color: t.textMuted, marginTop: 4, letterSpacing: "0.06em" },
    feedbackBody: { padding: "16px 18px", display: "flex", flexDirection: "column", gap: 12 },
    feedbackLabel: { display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 11, color: t.navColor, letterSpacing: "0.08em" },
    doneToggle: { display: "flex", gap: 4 },
    doneBtn: {
      background: t.surface2, border: `1px solid ${t.btnBorder}`, color: t.textMuted,
      padding: "4px 14px", borderRadius: 4, cursor: "pointer", fontSize: 11, fontFamily: "inherit",
    },
    doneBtnActive: { background: t.accentBg, border: `1px solid ${t.accentBorder}`, color: t.accent },
    doneBtnActiveNeg: { background: t.negativeBg, border: `1px solid ${t.negativeBorder}`, color: t.negativeColor },
    rpeValue: { fontSize: 16, fontWeight: 700 },
    slider: { width: "100%", accentColor: t.accent, cursor: "pointer" },
    stars: { display: "flex", gap: 4 },
    star: { background: "none", border: "none", cursor: "pointer", fontSize: 20, padding: 0, lineHeight: 1 },
    starEmpty: t.starEmpty,
    textarea: {
      background: t.inputBg, border: `1px solid ${t.btnBorder}`, color: t.textTitle,
      padding: "8px 10px", borderRadius: 6, fontSize: 11, fontFamily: "inherit", resize: "vertical", outline: "none",
    },
    feedbackFooter: { padding: "12px 18px", borderTop: `1px solid ${t.border}`, display: "flex", justifyContent: "flex-end", gap: 8 },
    cancelBtn: {
      background: "none", border: `1px solid ${t.btnBorder}`, color: t.textDim,
      padding: "7px 16px", borderRadius: 5, cursor: "pointer", fontSize: 11, fontFamily: "inherit",
    },
    saveBtn: {
      background: t.accentBg, border: `1px solid ${t.accentBorder}`, color: t.accent,
      padding: "7px 18px", borderRadius: 5, cursor: "pointer", fontSize: 11,
      fontFamily: "inherit", fontWeight: 700, letterSpacing: "0.06em",
    },
  };
}
